# Generated by Django 4.2 on 2023-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('piston_language', models.CharField(max_length=100)),
                ('piston_version', models.CharField(max_length=100)),
            ],
        ),
    ]
