# Generated by Django 4.2 on 2023-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_language_ace_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AceTheme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("ace_theme", models.CharField(max_length=100)),
            ],
        ),
    ]
