# Generated by Django 4.2 on 2023-04-25 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_acefont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('input', models.TextField()),
            ],
        ),
    ]
